routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('resource', 'ResourceController');

Route::resource('book', 'BookController');

Route::resource('project', 'ProjectController');

Route::resource('category', 'CategoryController');

Route::post('/', 'WelcomeController@email')->name('email');

Route::get('/', 'WelcomeController@welcome');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;

use App\Project;
use App\Category;

class ProjectController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        $categories = Category::all();

        return view('project.index')->withProjects($projects)->withCategories($categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('project.create')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate data
        $this->validate($request, array(
            'title' => 'required|max:50',
            'category_id' => 'required|integer',
            'description' => 'required|max:500',
            'source' => 'nullable|url',
            'view' => 'nullable|url'
        ));

        // store in the database
        $project = new Project;

        $project->title = $request->title;
        $project->category_id = $request->category_id;
        $project->description = $request->description;
        $project->source = $request->source;
        $project->view = $request->view;

        $project->save();

        Session::flash('success', 'A new Project has been added!');

        // redirect
        return redirect()->route('project.show', $project->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Project::find($id);
        $categories = Category::all();

        return view('project.show')->withProject($project)->withCategories($categories);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::find($id);
        $categories = Category::all();

        return view('project.edit')->withProject($project)->withCategories($categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validate data
        $this->validate($request, array(
            'title' => 'required|max:50',
            'category_id' => 'required|integer',
            'description' => 'required|max:500',
            'source' => 'nullable|url',
            'view' => 'nullable|url'
        ));

        // Store data
        $project = Project::find($id);

        $project->title = $request->title;
        $project->category_id = $request->category_id;
        $project->description = $request->description;
        $project->source = $request->source;
        $project->view = $request->view;

        $project->save();

        Session::flash('success', 'This Project has been updated!');

        // Redirect
        return redirect()->route('project.show', $project->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);
        
        $project->delete();
        
        Session::flash('success', 'The Project was successfully deleted!');
        
        return redirect()->route('project.index');
    }
}

resources/views/project/create.blade.php
@extends('main')

@section('title', '| Create Project')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Create Project</h3>
        <a href="{{ route('project.index') }}" class="btn-icon-primary lead"><i class="fas fa-times"></i></a>
      </div>
      <hr>
      <form action="{{ url('project') }}" method="POST">

        {{ csrf_field() }}

        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" class="form-control" name="title" placeholder="Make it catchy" value="{{ old('title') }}">
        </div>
        <div class="form-group">
          <label for="category_id">Category</label>
          <select class="form-control" name="category_id">
            <option>Select</option>
            @foreach($categories as $category)
            <option value="{{ $category->id }}">{{ $category->category }}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea class="form-control" name="description" placeholder="Make it brief and to the point" rows="4">{{ old('description') }}</textarea>
        </div>
        <div class="form-group">
          <label for="source">Source Code</label>
          <input type="text" class="form-control" name="source" placeholder="Link to the source code" value="{{ old('source') }}">
        </div>
        <div class="form-group">
          <label for="view">View</label>
          <input type="text" class="form-control" name="view" placeholder="Link to the code in action" value="{{ old('view') }}">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-block btn-outline-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

@stop

resources/views/project/edit.blade.php
@extends('main')

@section('title', '| Edit Project')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Edit Project</h3>
        <div>
          <a href="{{ route('project.show', $project->id) }}" class="btn-icon-primary lead mr-2"><i class="fas fa-eye"></i></a>
          <a href="{{ route('project.index') }}" class="btn-icon-primary lead"><i class="fas fa-times"></i></a>
        </div>
      </div>
      <hr>
      <form action="{{ url('project', $project->id) }}" method="POST">

        {{ method_field('PATCH') }}
        {{ csrf_field() }}

        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" class="form-control" name="title" placeholder="Make it catchy" value="{{ $project->title }}">
        </div>
        <div class="form-group">
          <label for="category_id">Category</label>
          <select class="form-control" name="category_id">
            <option>Select</option>
            @foreach($categories as $category)
            <option {{ $project->category_id == $category->id ? "selected" : "" }} value="{{ $category->id }}">{{ $category->category }}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea class="form-control" name="description" placeholder="Make it brief and to the point" rows="4">{{ $project->description }}</textarea>
        </div>
        <div class="form-group">
          <label for="source">Source Code</label>
          <input type="text" class="form-control" name="source" placeholder="Link to the source code" value="{{ $project->source }}">
        </div>
        <div class="form-group">
          <label for="view">View</label>
          <input type="text" class="form-control" name="view" placeholder="Link to the code in action" value="{{ $project->view }}">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-block btn-outline-primary">Update</button>
        </div>
      </form>
    </div>
  </div>
</div>

@stop

resources/views/project/index.blade.php
@extends('main')

@section('title', '| Projects')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-4 offset-md-1 mb-4">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Categories</h3>
        <div>  
          {{-- <a href="{{ route('dashboard') }}" class="btn-icon-primary lead mr-2"><i class="fas fa-arrow-left"></i></a> --}}
          <a href="{{ route('category.create') }}" class="btn-icon-primary lead"><i class="fas fa-plus"></i></a>
        </div>
      </div>
      <hr>
      <ul class="list-group">
        @foreach($categories as $category)
        <li class="d-flex justify-content-between list-group-item {{ $category->id == 1 ? "category-list-freecodecamp" : ($category->id == 2 ? "category-list-personal" : ($category->id == 3 ? "category-list-professional" : "category-list-progress")) }}">
          {{ $category->category }}
          <a class="{{ $category->id == 1 ? "category-list-btn-freecodecamp" : ($category->id == 2 ? "category-list-btn-personal" : ($category->id == 3 ? "category-list-btn-professional" : "category-list-btn-progress")) }}" href="{{ route('category.edit', $category->id) }}"><i class="fas fa-edit"></i></a>
        </li>
        @endforeach
      </ul>
      <small>Please Note: that if you create a new category you will have to create the custom css too.</small>
    </div>
    <div class="col-md-6">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Projects</h3>
        <div>  
          {{-- <a href="{{ route('dashboard') }}" class="btn-icon-primary lead mr-2"><i class="fas fa-arrow-left"></i></a> --}}
          <a href="{{ route('project.create') }}" class="btn-icon-primary lead"><i class="fas fa-plus"></i></a>
        </div>
      </div>
      <hr>
      @foreach($projects as $project)
      <div class="card {{ $project->category_id == 1 ? "website-card-freecodecamp" : ($project->category_id == 2 ? "website-card-personal" : ($project->category_id == 3 ? "website-card-professional" : "website-card-progress")) }}">
        <div class="card-body">
          <h5 class="card-title">{{ $project->title }}</h5>
          <h6 class="card-subtitle">{{ $project->category->category }}</h6>
          <p class="card-text">{{ substr($project->description, 0, 100) }}...</p>
          <a href="{{ route('project.show', $project->id) }}" class="card-link">Show</a>
          <a href="{{ route('project.edit', $project->id) }}" class="card-link">Edit</a>
        </div>
      </div>
      @endforeach
    </div>
  </div>
</div>

@stop

resources/views/project/show.blade.php
@extends('main')

@section('title', '| Show Project')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Show Project</h3>
        <div>
          <button type="button" class="btn-icon-danger lead mr-2" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-trash-alt"></i></button>
          <a href="{{ route('project.edit', $project->id) }}" class="btn-icon-primary lead mr-2"><i class="fas fa-edit"></i></a>
          <a href="{{ route('project.index') }}" class="btn-icon-primary lead"><i class="fas fa-times"></i></a>
        </div>
      </div>
      <hr>
      <form>
        <div class="form-group">
          <label for="title">Title</label>
          <p readonly class="form-control-plaintext">{{ $project->title }}</p>
        </div>
        <div class="form-group">
          <label for="category_id">Category</label>
          <p readonly class="form-control-plaintext">{{ $project->category->category }}</p>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <p readonly class="form-control-plaintext">{{ $project->description }}</p>
        </div>
        <div class="form-group">
          <label for="source">Source Code</label>
          <a readonly class="form-control-plaintext link-primary" href="{{ $project->source }}">{{ $project->source }}</a>
        </div>
        <div class="form-group">
          <label for="view">View</label>
          <a readonly class="form-control-plaintext link-primary" href="{{ $project->view }}">{{ $project->view }}</a>
        </div>
        <div class="form-group d-flex justify-content-between">
          <small>{{ date('M j, Y H:i', strtotime($project->created_at)) }}</small>
          <small>{{ date('M j, Y H:i', strtotime($project->updated_at)) }}</small>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this Project?</p>
        <form action="{{ url('project', $project->id) }}" method="POST">

          {{ method_field('DELETE') }}
          {{ csrf_field() }}

          <button type="submit" class="btn btn-danger btn-block">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

@stop