routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('resource', 'ResourceController');

Route::resource('book', 'BookController');

Route::resource('project', 'ProjectController');

Route::resource('category', 'CategoryController');

Route::post('/', 'WelcomeController@email')->name('email');

Route::get('/', 'WelcomeController@welcome');

resources/views/partials/app/_footer.blade.php
<footer class="container-fluid fixed-bottom bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="text-center mt-2 mb-2"> CrestWorks <i class="fas fa-copyright"></i></p>
      </div>
    </div>
  </div>
</footer>

resources/views/partials/app/_messages.blade.php
{{-- <div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3"> --}}
  
      @if (Session::has('success'))
  
        <div class="alert alert-message alert-success alert-dismissible text-center" role="alert">
          <strong>Success:</strong> {{ Session::get('success') }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
  
      @endif
  
      @if (count($errors))
  
        <div class="alert alert-message alert-danger alert-dismissible text-center m-0" role="alert">
          <strong>Error(s):</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
  
      @endif
  
    {{-- </div>
  </div>
</div> --}}

resources/views/partials/app/_nav.blade.php
<nav class="navbar navbar-expand-md navbar-light pt-4">
  <div class="container">
    <a class="navbar-brand" href="/">CrestWorks</a>
    <p class="m-0">{{ Auth::check() ? Auth::user()->name : '' }}</p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        @if(Auth::check())
        <li class="nav-item">
          <a class="nav-link" href="{{ route('dashboard') }}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('project.index') }}">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('book.index') }}">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('resource.index') }}">Resources</a>
        </li>
        <li class="nav-item">
          <form action="{{ url('logout') }}" method="POST">
            {{ csrf_field() }}
            <button class="nav-link">Logout</button>
          </form>
        </li>
        @else
        <li class="nav-item">
          <a class="nav-link" href="/">Landing Page</a>
        </li>
        @endif
      </ul>
    </div>
  </div>
</nav>