routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('resource', 'ResourceController');

Route::resource('book', 'BookController');

Route::resource('project', 'ProjectController');

Route::resource('category', 'CategoryController');

Route::post('/', 'WelcomeController@email')->name('email');

Route::get('/', 'WelcomeController@welcome');

resources/views/resource/create.blade.php
@extends('main')

@section('title', '| Create Resource')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Create Resource</h3>
        <a href="{{ route('resource.index') }}" class="btn-icon-primary lead"><i class="fas fa-times"></i></a>
      </div>
      <hr>
      <form action="{{ url('resource') }}" method="POST">

        {{ csrf_field() }}

        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" placeholder="Name of resource" value="{{ old('resource') }}">
        </div>
        <div class="form-group">
          <label for="link">Link</label>
          <input type="text" class="form-control" name="link" placeholder="Link to resource" value="{{ old('link') }}">
      </div>
        <div class="form-group">
          <button type="submit" class="btn btn-block btn-outline-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

@stop

resources/views/resource/edit.blade.php
@extends('main')

@section('title', '| Edit Resource')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Edit Resource</h3>
        <div>
          <button type="button" class="btn-icon-danger lead mr-2" data-toggle="modal" data-target="#deleteModal"><i class="fas fa-trash-alt"></i></button>
          <a href="{{ route('resource.index') }}" class="btn-icon-primary lead"><i class="fas fa-times"></i></a>
        </div>
      </div>
      <hr>
      <form action="{{ url('resource', $resource->id) }}" method="POST">

        {{ method_field('PATCH') }}
        {{ csrf_field() }}

        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" placeholder="Resource name" value="{{ $resource->name }}">
        </div>
        <div class="form-group">
          <label for="link">Link</label>
          <input type="text" class="form-control" name="link" placeholder="Link to resource" value="{{ $resource->link }}">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-block btn-outline-primary">Update</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this Resource?</p>
          <form action="{{ url('resource', $resource->id) }}" method="POST">
  
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
  
            <button type="submit" class="btn btn-danger btn-block">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

@stop

resources/views/resource/index.blade.php
@extends('main')

@section('title', '| Resources')

@section('content')

<div class="container mt-4 pb-80">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="d-flex justify-content-between align-items-baseline">
        <h3>Resources</h3>
        <div>  
          {{-- <a href="{{ route('dashboard') }}" class="btn-icon-primary lead mr-2"><i class="fas fa-arrow-left"></i></a> --}}
          <a href="{{ route('resource.create') }}" class="btn-icon-primary lead"><i class="fas fa-plus"></i></a>
        </div>
      </div>
      <hr>
      <ul class="list-group list">
        @foreach($resources as $resource)
        <li class="list-group-item d-flex justify-content-between align-items-center list-item">
          <div>
            <p class="mb-1">{{ $resource->name }}</p>
            <a href="{{ $resource->link }}" class="list-item-link"><small>Resource Link</small></a>
          </div>
          <a href="{{ route('resource.edit', $resource->id) }}" class="list-item-link"><i class="fas fa-edit"></i></a>
        </li>
        @endforeach
      </ul>
    </div>
  </div>
</div>

@stop